# Generated by Django 5.2 on 2025-04-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkYeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=20)),
                ('giris_zamani', models.DateTimeField(auto_now_add=True)),
                ('cikis_zamani', models.DateTimeField(blank=True, null=True)),
                ('aktif_mi', models.BooleanField(default=True)),
            ],
        ),
    ]
