# Generated by Django 5.2 on 2025-05-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_parkinglocation_delete_parkyeri'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglocation',
            name='map_url',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='video_url',
            field=models.URLField(default='https://example.com/video'),
        ),
    ]
